### ISSUE TITLE
[v3] Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/common-lisp#333]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/common-lisp/issues/324)
- [x] [Add key features](https://github.com/exercism/common-lisp/issues/325)
- [x] [Add tags](https://github.com/exercism/common-lisp/issues/326)
- [x] [Add prerequisites to Practice Exercises](https://github.com/exercism/common-lisp/issues/327)
- [x] [Update status of track](https://github.com/exercism/common-lisp/issues/331)
- [x] [Update status of Concept Exercises](https://github.com/exercism/common-lisp/issues/332)
- [x] [Pass linting checks](https://github.com/exercism/common-lisp/issues/328)
- [x] [Build Test Runner](https://github.com/exercism/common-lisp/issues/329)
- [x] [Build Analyzer and Representer](https://github.com/exercism/common-lisp/issues/330) (optional)
- [x] [Add blurb to Concept Exercises](https://github.com/exercism/common-lisp/issues/369)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7

**Comment by verdammelt** [comment]
While i just merged PRs for prerequisites on practice exercises - i'm not going to check it off yet because i don't think that work is "done".
