### ISSUE TITLE
V3: MUST-DO list

### ISSUE THREAD

**Issue by verdammelt** [exercism/common-lisp#380]
A list of issues that I feel must be resolved before the track is ready for general use in v3. This is not meant to be all issues needed to get the track to 100% awesomeness. Just to get it to 0% brokenness.

(If an item on the list does not link to an issue then first step is to create an issue so it can be listed here.)

- [x] Strings concept (needed for sameness and pal-picker concept exercises) #311 
- [x] fix concept authors lists (cannot be empty anymore) #390
- [ ] Characters concept (needed for sameness concept exercise) #320 
- [ ] Arrays concept (needed for sameness concept exercise)  #407
- [x] Update README (PR #398 )
- [x] Concepts need blurbs! (esp those mentioned in concept exercises!)
- [x] Concepts need about/introduction files (esp. those mentioned in concept exercises!)
- [x] Installation instructions wrong #376 
- [x] testing instructions wrong #376 
- [ ] Shared files for track needed #355 
- [ ] pizza-pi instructions use MathJax which is not yet supported - remove for now.

**Comment by verdammelt** [comment]
Reviewing the concepts provided by concept exercises vs. the list of concepts needed by concept exercises I see that characters, strings and arrays concepts are a bottle-neck. Specifically strings is blocking two concept exercises.

**Comment by verdammelt** [comment]
I've decided that this meta issue is not helping me at all - instead I'll create specific issues with a proper tag.

**Comment by verdammelt** [comment]
Closing this in preference of individual issues with a `v3` tag.
